CREATE DATABASE EvoluirEducacao;

USE EvoluirEducacao;

CREATE TABLE Curso(
	IdCurso UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome VARCHAR(100) NOT NULL,
	Duracao INT NOT NULL,
	Periodo VARCHAR(100) NOT NULL,
	CargaHoraria INT NOT NULL,
);
GO

SELECT * FROM Curso;

CREATE TABLE Turma(
	IdTurma UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome VARCHAR(100) NOT NULL,
	Turno VARCHAR(50) NOT NULL,
	Capacidade INT NOT NULL,

	-- Importa a chave estrangeira
	IdCurso UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Curso(IdCurso)
);
GO

SELECT * FROM Turma;

CREATE TABLE Aluno(
	IdAluno UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome VARCHAR(100) NOT NULL,
	Matricula VARCHAR(255) NOT NULL,
	Foto VARCHAR(150) NOT NULL,
	Contato INT NOT NULL,

	--Importa a chave estrangeira
	IdTurma UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Turma(IdTurma)
);
GO

SELECT * FROM Aluno;